### ISSUE TITLE
Postgres down & rollback not dropping tables

### ISSUE THREAD

**Issue by m1rm** [knex/knex#5773]
# Environment

Knex version: 3.0.1
Database + version: Postgres 16 in Docker
Node version: 20.10.0
OS: Arch Linux

# Bug
## Description
According to [the dropTableIfExists documentation](https://knexjs.org/guide/schema-builder.html#droptableifexists) for the down-method of a migration, I expect the table to be dropped. But the table is not dropped.

## commands executed
`UID="$(id -u)" GID="$(id -g)" docker compose run my-app npm run knex:migrations:rollback`
or
`UID="$(id -u)" GID="$(id -g)" docker compose run my-app npm run knex:migrations:down`

## Error message
```
> knex migrate:rollback

Requiring external module ts-node/register
Using environment: development
Batch 1 rolled back: 2 migrations
```
`docker compose logs -f` shows no activity when executing the knex commands, no errors, just nothing.

### Migration Code
```
import { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
    knex.schema.hasTable('showcase').then(function(exists) {
        if (!exists) {
          return knex.schema.createTable('showcase', function(t) {
            t.increments('id').primary();
            t.string('first_name', 100);
            t.string('last_name', 100);
            t.text('bio');
          });
        }
      });
}

export async function down(knex: Knex): Promise<void> {
    knex.schema.dropTableIfExists('showcase');
}
```

### knexfile
```
import type { Knex } from "knex";

const config: { [key: string]: Knex.Config } = {
  development: {
    client: 'pg',
    connection: {
      host : 'my-db',
      user : 'myuser',
      password : 'mypassword',
      database : 'mydb',
      charset: 'utf8'
    },
    migrations: {
      directory: __dirname + '/knex/migrations',
    },
    seeds: {
      directory: __dirname + '/knex/seeds'
    }
  },
// TODO: setup for staging & production
// after this line: autogenerated code not relevant for this issue
```
### package.json
```
{
  "name": "myShowcase",
  "version": "0.1.0",
  "description": "Bug Showcase",
  "engines": {
    "node": ">=20",
    "npm": ">=10"
  },
  "main": "dist/main.js",
  "scripts": {
    "dev": "nodemon",
    "lint": "eslint .",
    "test": "jest --config jest.config.ts --coverage",
    "build": "tsc --project tsconfig.build.json",
    "ts": "ts-node src/main.ts",
    "knex:migrations:make": "knex migrate:make",
    "knex:migrations:latest": "knex migrate:latest",
    "knex:migrations:up":"knex migrate:up",
    "knex:migrations:list":"knex migrate:list",
    "knex:migrations:down":"knex migrate:down",
    "knex:migrations:rollback": "knex migrate:rollback"
  },
  "author": "miriam mueller",
  "license": "",
  "dependencies": {
    "@hapi/hapi": "^21.3.0",
    "@hapi/inert": "^7.1.0",
    "@hapi/vision": "^7.0.3",
    "@types/pg": "^8.10.9",
    "config": "^3.3.9",
    "graphlib": "^2.1.8",
    "hapi-swagger": "^17.2.0",
    "joi": "^17.11.0",
    "knex": "^3.0.1",
    "node-cache": "^5.1.2",
    "pg": "^8.11.3",
    "pino": "^8.11.0",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "@types/config": "^3.3.0",
    "@types/graphlib": "^2.1.11",
    "@types/hapi": "^18.0.8",
    "@types/jest": "^29.4.0",
    "@types/mysql": "^2.15.24",
    "@types/node": "^20.9.2",
    "@types/uuid": "^9.0.7",
    "@typescript-eslint/eslint-plugin": "^6.11.0",
    "@typescript-eslint/parser": "^6.11.0",
    "eslint": "^8.35.0",
    "jest": "^29.5.0",
    "nodemon": "^3.0.1",
    "ts-jest": "^29.0.5",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  }
}

```

### compose.yml
```
version: '3.7'
services:
  my-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
    volumes:
      - "database_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  my-app:
    user: "${UID}:${GID}"
    userns_mode: host
    build: 
      context: .
      target: dev-stage
    volumes:
      - ./src:/usr/src/app/src
      - ./knex:/usr/src/app/knex
      - ./config:/usr/src/app/config
    ports:
      - "9033:9033"
    depends_on: 
    - "my-db"
volumes:
  database_data:
    driver: "local"
```
## What I also tried
- using `knex.schema.withSchema('sys').hasTable`
as described in https://github.com/knex/knex/issues/5435

Where did I take a wrong turn? Can anybody reproduce?
